apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: {{ .Release.Name }}-{{ include ".helm.fullname" . }}-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.global.configCapacity }}
  nfs:
    path: {{ .Values.global.configPath }}{{ .Values.configPath }}
    server: {{ .Values.global.nfs.server }}
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: {{ .Release.Name }}-{{ include ".helm.fullname" . }}-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.configCapacity }}
  selector: {}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ .Release.Name }}-{{ include ".helm.fullname" . }}-pv